server:
  port: 8887
eureka:
  instance:
    hostname: eureka2
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:123456@aitieta.com:8888/eureka/,http://root:123456@aitieta.com:8887/eureka/
#    eureka-server-read-timeout-seconds: 100000
#  server:
#    peer-node-read-timeout-ms: 100000
spring:
  application:
    name: register-center
  security:
    user:
      name: root
      password: 123456
